version: '3.8'

services:
  client:
    image: ../client
    ports:
      - "1992:2007"
    depends_on:
      - server
    restart: always

  server:
    build: ./server
    ports:
      - "2023:3000"
    restart: always